//
//  MessageThemeView.swift
//  WishKit
//
//  Created by diayan siat on 31/10/2025.
//

import SwiftUI

struct MessageThemeView: View {
    @State private var selectedTheme: Theme? = nil
    @State private var themeName: String = ""
    @State private var messageLength: MessageLength? = nil
    @State private var includeEmojis: Bool = false
    @State private var customNotes: String = ""
    @State private var isButtonAnimating: Bool = false
    @State private var showGeneratedMessage: Bool = false
    @State private var isAnimated: Bool = false
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        ZStack {
            AppColors.backgroundGradient(for: colorScheme)
                .ignoresSafeArea()

            VStack(spacing: 0) {
                HeaderView(title: "What's the vibe?", currentStep: 1)

                ScrollView(.vertical, showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 40) {
                        ThemeSelectionSection(
                            selectedTheme: $selectedTheme,
                            themeName: $themeName
                        )
                        .opacity(isAnimated ? 1 : 0)
                        .offset(y: isAnimated ? 0 : 20)

                        MessageLengthSection(selectedLength: $messageLength)
                            .opacity(isAnimated ? 1 : 0)
                            .offset(y: isAnimated ? 0 : 20)

                        EmojiToggleSection(includeEmojis: $includeEmojis)
                            .opacity(isAnimated ? 1 : 0)
                            .offset(y: isAnimated ? 0 : 20)

                        CustomNotesSection(customNotes: $customNotes)
                            .opacity(isAnimated ? 1 : 0)
                            .offset(y: isAnimated ? 0 : 20)

                        GenerateMessageButton(isAnimating: $isButtonAnimating) {
                            showGeneratedMessage = true
                        }
                        .padding(.top, 16)
                        .opacity(isAnimated ? 1 : 0)
                        .offset(y: isAnimated ? 0 : 20)

                        Spacer(minLength: 40)
                    }
                    .padding(.horizontal, 24)
                    .padding(.top, 24)
                }
            }
        }
        .navigationBarBackButtonHidden(false)
        .onAppear {
            withAnimation(.spring(response: 0.6, dampingFraction: 0.75)) {
                isAnimated = true
            }
        }
        .sheet(isPresented: $showGeneratedMessage) {
            GeneratedMessageView(
                recipientName: "Sarah",
                occasion: "Birthday",
                theme: themeName.isEmpty ? nil : themeName,
                messageText: "✨ Happy Birthday, Sarah! May your day sparkle with a little mischief, a touch of magic, and the wonder of a well-cast charm. Here's to another year of adventures, friendships as loyal as a Patronus, and dreams as limitless as the wizarding world itself. Wishing you all the joy and happiness today! 🪄\n\nThis is your generated message based on your selected theme and preferences. The actual message will be generated by AI based on all the information you provided."
            )
            .presentationDetents([.large])
            .presentationDragIndicator(.visible)
            .presentationCornerRadius(28)
        }
    }
}

#Preview {
    MessageThemeView()
}
